"""
config/settings.py
Central configuration for the research agent.
"""

from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR   = Path(__file__).resolve().parent.parent
DATA_DIR   = BASE_DIR / "data"
CACHE_DIR  = DATA_DIR / "cache"
REPORT_DIR = DATA_DIR

# Auto-create directories
CACHE_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# ── Ollama / LLM ──────────────────────────────────────────────────────────────
OLLAMA_BASE_URL  = "http://localhost:11434"
OLLAMA_MODEL     = "llama3"          # swap to "mistral", "gemma2", etc.
LLM_TEMPERATURE  = 0.2               # low for factual extraction
LLM_MAX_TOKENS   = 4096

# ── Search ─────────────────────────────────────────────────────────────────────
MAX_SEARCH_RESULTS   = 8             # results per query
MAX_SCRAPE_CHARS     = 3000          # chars to keep from each scraped page
SEARCH_QUERIES_COUNT = 3             # how many different queries to run

# ── Agent loop ─────────────────────────────────────────────────────────────────
MIN_COMPETITORS      = 3             # minimum distinct competitors needed
MAX_RETRY_LOOPS      = 2             # re-search iterations before giving up
SUFFICIENT_DATA_KEYS = [             # fields we need per competitor
    "name", "pricing", "key_features", "target_market",
]

# ── Report ──────────────────────────────────────────────────────────────────────
REPORT_TITLE    = "Competitive Market Analysis"
REPORT_SUBTITLE = "AI-generated by Research Agent"
